---
- name: Ping EC2 Instances
  hosts: all  # Replace with the desired group or host from your dynamic inventory
  gather_facts: no  # Disable gathering facts for faster execution
  tasks:
    - name: Ping the EC2 instances
      ping:
